### ISSUE TITLE
Cache restore missing some of the modules

### ISSUE THREAD

**Issue by beau-witter** [potatoqualitee/psmodulecache#45]
When there was a cache miss and the modules needed to be installed, my workflow worked just fine and the build was able to complete as shown here.
![cache_save](https://user-images.githubusercontent.com/26094186/217048069-588fcd0c-2e1f-48eb-bf95-a6ec46d9b7fd.PNG)

Once that was saved, however, the proceeding runs all fail with the same error. It appears that the module "PlatyPS" is not being correctly imported by the cacher
![cacher_malfunction](https://user-images.githubusercontent.com/26094186/217048071-53ff0799-9ca7-43c2-ba29-2916b69455a3.PNG)

**Comment by LaurentDardenne** [comment]
Hi,
where can I read the code and the logs of the Action used?

**Comment by beau-witter** [comment]
https://github.com/vexx32/PSKoans/actions/runs/4106356511/jobs/7084476447

**Comment by LaurentDardenne** [comment]
Thanks.
Coul you delete the cache file 'Linux-5.0-Immutable-pwsh-PSDeploy-BuildHelpers-PlatyPS-Pester:5.0.2-EZOut' and run again the Action ?

**Comment by beau-witter** [comment]
> Thanks. Coul you delete the cache file 'Linux-5.0-Immutable-pwsh-PSDeploy-BuildHelpers-PlatyPS-Pester:5.0.2-EZOut' and run again the Action ?

I do not have write access to the repo. I cannot delete the cache.

**Comment by LaurentDardenne** [comment]
Ok, I try to repro this issue.

>>I do not have write access to the repo. I cannot delete the cache.

To test, you can force the cache update by adding another module name, this creates a new cache key.

**Comment by LaurentDardenne** [comment]
I reproduce the error, I would test with the new version of the 'Cache' action.

**Comment by beau-witter** [comment]
Oh my, I can't believe it was a casing issue. Problem solved then. Thanks a ton!

**Comment by LaurentDardenne** [comment]
@potatoqualitee 
Hi, can you add the 'Bug' label and reopen this issue ?

The construction of the path name, during Save-Module, comes from the nuget package and not from the contents of the 'modules-to-cache' parameter :
![image](https://user-images.githubusercontent.com/4894452/217232979-b5de805c-1640-439e-8b22-e368973d1480.png)

It's more a bug due to the behavior of PowershellGet. The contents of parameters targeting module names are case-insensitive except when writing to disk by PSGet(name of the nuget package generated when published). This case was not highlighted during my tests.

Moreover, I think that the dependent modules (present in a manifest), are not saved in the cache, I will check as soon as I have time.
